### ISSUE TITLE
OutOfAfricaArchaicAdmixture_5R19 error with "none" config for DFE/annotation

### ISSUE THREAD

**Issue by lntran26** [popsim-consortium/analysis2#109]
When running production config for humans, I got this error that seems to be specific to the OutOfAfricaArchaicAdmixture_5R19 demographic model. (I didn't have this error when trying the "OutOfAfrica_3G09" demography--but take that with a grain of salt because we're also currently having the error mentioned in [this issue](https://github.com/popsim-consortium/stdpopsim/issues/1551) with other config settings)
```
TypeError in file /xdisk/rgutenk/lnt/projects/stdpopsim/analysis2/workflows/simulation.snake, line 93:
unsupported operand type(s) for *: 'NoneType' and 'int'
  File "/xdisk/rgutenk/lnt/projects/stdpopsim/analysis2/workflows/simulation.snake", line 93, in __rule_simulation
  File "/home/u30/lnt/micromamba/envs/analysis2/lib/python3.10/site-packages/stdpopsim/slim_engine.py", line 1626, in simulate
  File "/home/u30/lnt/micromamba/envs/analysis2/lib/python3.10/site-packages/stdpopsim/slim_engine.py", line 744, in get_slim_mutation_rate_map
  File "/home/u30/lnt/micromamba/envs/analysis2/lib/python3.10/concurrent/futures/thread.py", line 58, in run
```
The specific lines of code mentioned in the error are these:
`slim_rates = contig.mutation_rate * slim_fractions[dfe_labels]` from [here](https://github.com/popsim-consortium/stdpopsim/blob/fbb94c223751653889743df0cedf2153ff304ed7/stdpopsim/slim_engine.py#L744)
and 
`slim_rate_map = get_slim_mutation_rate_map(contig)` from [here](https://github.com/popsim-consortium/stdpopsim/blob/fbb94c223751653889743df0cedf2153ff304ed7/stdpopsim/slim_engine.py#L1626)
Any insight into what the problem might be would be helpful!

**Comment by petrelharp** [comment]
The first thing I'd do here is to try to make the error happen not in snakemake?

**Comment by lntran26** [comment]
I think I found the problem. There is no mutation rate set for the OutOfAfricaArchaicAdmixture_5R19 [model](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/demographic_models.py#L658) so `contig.mutation_rate` is none. Seems like this is by design for this demographic model so if we want to use this model for the paper then we will need to modify the pipeline code, which asks for the model mutation rate [here](https://github.com/popsim-consortium/analysis2/blob/main/workflows/simulation.snake#L71). In the first [analysis](https://github.com/popsim-consortium/analysis/blob/master/n_t/Snakefile#L89) paper that uses this model, it seems like a mean species mutation rate was used instead of the model-specific mutation rate.

**Comment by mufernando** [comment]
did we fix this?
