### ISSUE TITLE
QC of the zoo (?)

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/analysis2#14]
I was just thinking here that as part of the second paper we could show that stdpopsim has increased its catalog by XX amount of species, and that it has also increased its number of users (not sure how to measure that, maybe Github installs?). 

I can see, however, that there are plenty of species to be added, and maybe some people could focus their time on the QC of those species?

**Comment by jeromekelleher** [comment]
I think we would have to do a fair bit of QC on the new additions all right @izabelcavassim.

Re number of users, we could quote pypi and conda installation stats, but these are hard to interpret because of things like automated installs in CI pipelines.

**Comment by izabelcavassim** [comment]
closing this issue since it is duplicated https://github.com/popsim-consortium/stdpopsim/issues/1069
