### ISSUE TITLE
Verification of slim Huber et al 2017 (Human)

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/analysis2#15]
The original script for Huber Human et al 2017 is:

[Hubber_gamma.txt](https://github.com/popsim-consortium/analysis2/files/7001487/Hubber_gamma.txt)

We need to verify whether stdpopsim is outputting the same features as in the script above.

**Comment by xin-huang** [comment]
Hi Izabel,

Here is the slim script for simulating the Gutenkunst09 demographic model with the Huber DFE:

[Hum_Gutenkunst09_HuberDFE.slim.txt](https://github.com/popsim-consortium/analysis2/files/7039827/Hum_Gutenkunst09_HuberDFE.slim.txt)

I used the following command to generate the data

```slim -s 123 -d FACTOR=1 -d SEQSIZE=248955 Hum_Gutenkunst09_HuberDFE.slim.txt```

```import dadi
fnames = ['p1.slimout', 'p2.slimout', 'p3.slimout']
dd_syn, ns = dadi.Misc.dd_from_SLiM_files(fnames, mut_types=['m1'])
dd_non, ns = dadi.Misc.dd_from_SLiM_files(fnames, mut_types=['m2'])
popids = range(len(ns))
fs_syn = dadi.Spectrum.from_data_dict(dd_syn, popids, ns)
fs_non = dadi.Spectrum.from_data_dict(dd_non, popids, ns)

num_neutral = fs_syn.S()
num_nonneu = fs_non.S()

print(
    f"There are {num_neutral} neutral mutations, and "
    f"{num_nonneu} nonneutral mutations."
)
```

I got 

```There are 511.0 neutral mutations, and 638.0 nonneutral mutations.```

I also used the codes from https://stdpopsim.readthedocs.io/en/latest/tutorial.html#incorporating-selection to simulate the Gutenkunst09 demographic model with the Huber DFE

```
def HuberDFE():
    """
    Return neutral and negative MutationType()s representing a human DFE.
    Huber et al. (2017)
    """
    neutral = stdpopsim.ext.MutationType()
    gamma_shape = 0.19  # shape
    gamma_mean = -0.014  # expected value
    h = 0.5  # dominance coefficient
    negative = stdpopsim.ext.MutationType(
        dominance_coeff=h,
        distribution_type="g",  # gamma distribution
        distribution_args=[gamma_mean, gamma_shape],
    )
    # neutral mutations have 0 proportion because they are not simulated by SLiM
    return {"mutation_types": [neutral, negative], "proportions": [0.0, 0.7]}


species = stdpopsim.get_species("HomSap")
model = species.get_demographic_model("OutOfAfrica_3G09")
contig = species.get_contig("chr1", length_multiplier=0.001)
contig.clear_genomic_mutation_types()
samples = model.get_samples(100, 100, 100)  # YRI, CEU, CHB

# neutral and deleterious mutations occur across the whole contig
contig.add_genomic_element_type(
    intervals=np.array([[0, int(contig.recombination_map.sequence_length)]]),
    **HuberDFE(),
)

engine = stdpopsim.get_engine("slim")
ts = engine.simulate(
    model,
    contig,
    samples,
    seed=123,
    slim_scaling_factor=1,
    slim_burn_in=10,
    #slim_script=True
)

mut_info = {}
for mut in ts.mutations():
    for j, md in zip(mut.derived_state.split(","), mut.metadata["mutation_list"]):
        if j not in mut_info:
            mut_info[int(j)] = md

num_neutral = sum([mut_info[j]["selection_coeff"] == 0.0 for j in mut_info])
print(
    f"There are {num_neutral} neutral mutations, and "
    f"{len(mut_info) - num_neutral} nonneutral mutations."
)
```

The result is

```There are 288 neutral mutations, and 400 nonneutral mutations.```

I printed out the slim script generated by stdpopsim and found the mutation rate became 9.029999999999999e-09. The genome-wide mutation rate is 2.35e-8 (https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/demographic_models.py#L60). Because we only simulate mutations with negative selection here, shouldn't the mutation rate be 2.35e-8 * 0.7 = 1.645e-8?

**Comment by izabelcavassim** [comment]
I don't think \mu will change but we expect \theta_nonsynonymous (4Nemu*L) to be different than the synonymous one (given the 0.3, 0.7 proportions). If you do not set a specific mutation rate in your script, I believe it defaults to the mutation rate of the contig (chr1) you are simulating from, which is supposed to be: 1.29e-08 (https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_HomSap). 
Not sure why it changes to 9.029999999999999e-09. 

To set a specific mutation rate you can just do:
contig.mutation_rate = 2.35e-8

Can you try setting this contig_mutation rate and check whether we get closer results?
Thank you!

**Comment by xin-huang** [comment]
Yes, after setting `contig.mutation_rate = 2.35e-8`, then the mutation rate in the slim script became 1.645e-8.

And the result is

`There are 453 neutral mutations, and 749 nonneutral mutations.`

**Comment by izabelcavassim** [comment]
The contig recombination rate is the same as the one used by Huber, right?
contig.recombination_rate = 1.1485597641285933e-08

What else is different in Huber's script compared to the stdpopsim?

**Comment by xin-huang** [comment]
I just copied the recombination rate from the stdpopsim script to make all the parameters consistent.

Another difference is I simulated both neutral and non-neutral mutations in SLiM.
Maybe I can try use tree-sequence to simulate only non-neutral mutations with SLiM and add neutral mutations back with msprime.

**Comment by xin-huang** [comment]
I found `stdpopsim` uses `late event` in demographic models
Now the results are similar after using `late event` in my SLiM script

[Hum_OutOfAfrica3G09_HuberDFE.late.slim.txt](https://github.com/popsim-consortium/analysis2/files/7112383/Hum_OutOfAfrica3G09_HuberDFE.late.slim.txt)
[stdpopsim_OutOfAfrica3G09_HuberDFE.py.txt](https://github.com/popsim-consortium/analysis2/files/7112384/stdpopsim_OutOfAfrica3G09_HuberDFE.py.txt)

![comparision](https://user-images.githubusercontent.com/12013600/132141983-3e2bf0d3-0b7e-42cf-8719-e4fb54f3ebed.png)

**Comment by grahamgower** [comment]
Hi @xin-huang. Yes, the slim engine in stdpopsim uses `late` events. I'm surprised that this is the cause of the discrepancy though. Do you have any idea of why this causes such a difference?

**Comment by xin-huang** [comment]
Hi @grahamgower I think `late` events cause some difference in generations and affect the number of mutations, but would not affect the proportion of mutations much.

![comparision](https://user-images.githubusercontent.com/12013600/132254687-86d74f6b-ae3e-4a4c-bcc5-ae32e03365f2.png)
