### ISSUE TITLE
move/adapt demographic model benchmarking code from first paper

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#2]
One goal is to re-do some of our benchmarking of demographic inference, for which we can re-use code from our first paper (https://github.com/popsim-consortium/analysis) - so, we need to move appropriate bits of that workflow over here and adapt it.

Probably the first steps are to:
- pick a figure in the paper to replicate
- get the code from `analysis/` working here on a very simple model with selection (one that runs very quick, for debugging purposes)

**Comment by izabelcavassim** [comment]
We got it in now https://github.com/popsim-consortium/analysis2/pull/30 and work done by @andrewkern on https://github.com/popsim-consortium/analysis2/pull/37. Can you close this @petrelharp? For some reason, I can't.

**Comment by izabelcavassim** [comment]
I will close it because most of it is almost in with #40
