### ISSUE TITLE
verify analysis2 pipeline elsewhere

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#20]
@chriscrsmith was going to run the pipeline elsewhere to make sure things work on a different computer. (ok, @chriscrsmith?)

**Comment by izabelcavassim** [comment]
I think @andrewkern has done it. And we should all be testing the new merged pipeline in our own computers/clusters anyway.

**Comment by chriscrsmith** [comment]
This is from December? Sorry I didn't notice this!

I am actually getting some errors running inference.snake on my computer... still looking at it.

**Comment by chriscrsmith** [comment]
My bug was form checking out an earlier version of Andy's PR. Looks good now.

**Comment by andrewkern** [comment]
i'm going to close this issue as the pipeline is definitely portable. we still have build out to do and then, eventually, production runs
