### ISSUE TITLE
make requirements.txt file

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#24]

**Comment by andrewkern** [comment]
yeah we need a requirements.txt that will do all of the installation we need including more esoteric stuff like @xin-huang's `dadi-cli` that is [here](https://github.com/xin-huang/dadi-cli)

**Comment by xin-huang** [comment]
polyDFE: https://github.com/paula-tataru/polyDFE
DFE-alpha: http://www.homepages.ed.ac.uk/pkeightl//dfe_alpha/dfe-alpha-download.html
anavar: https://github.com/drkaizeng/publications-and-software/tree/main/anavar

Both `DFE-alpha` and `anavar` need to be complied by users with `gsl` and `nlopt`. Should we make a file similar to [this](https://github.com/popsim-consortium/analysis/blob/master/extern/msmc_makefile_stdpopsim_patch)?

**Comment by andrewkern** [comment]
sure yeah, but let's not do that on this PR.

**Comment by izabelcavassim** [comment]
For this newly compiled analysis2 pipeline @andrewkern. Does the requirements.txt file  in analysis2/ cover the full pipeline? If so then we can close this issue too.

**Comment by andrewkern** [comment]
yes, closed by #40
