### ISSUE TITLE
 move/adapt rescaling analysis code from first paper 

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#3]
We had some analysis of rescaling in the first paper; we can re-use that here.

A good place to start would be to:
- move the code over from `analysis/` and get it working on some simple test models
- modify it to insert some selection (still simple)

**Comment by izabelcavassim** [comment]
We got it in now #30 and work done by @andrewkern on #37. Can you close this @petrelharp? For some reason, I can't.

**Comment by izabelcavassim** [comment]
In progress, but I think we can close this now.
