### ISSUE TITLE
Identify selected mutation types from top-level metadata

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#32]
Currently [in the analysis code](https://github.com/popsim-consortium/analysis2/blob/6f5ff400223153ba5621dbcf6ddab15174f0b473/benchmark/Snakefile#L128) it is hard-coded that mutation type 3 is the "selected"; this information should be extracted from the metadata (after https://github.com/popsim-consortium/stdpopsim/pull/1152)

**Comment by izabelcavassim** [comment]
we got this in, right @mufernando?
