### ISSUE TITLE
DFE benchmark

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/analysis2#34]
Hi, 

Currently, we have three tools (`dadi`, `polyDFE`, and `DFE-alpha`) implemented in the analysis pipeline.

I think `dadi` perform better with large sample size and `polyDFE` perform better with small sample size and nuisance parameters.
`DFE-alpha` is widely used for inferring DFEs in different species, but it looks like E|s| is overestimated in `DFE-alpha`.

Other possible tools are
| tool | URL |
| - | - |
| grapes | https://github.com/BioPP/grapes |
| anavar | https://github.com/drkaizeng/publications-and-software/tree/main/anavar |

Demographic models we should test

- [x] Constant size model
- [x] `3G09_OutOfAfrica`

cc: @RyanGutenkunst @chriscrsmith

**Comment by RyanGutenkunst** [comment]
Thanks for opening the issue @xin-huang.

My vote is that we add grapes, but not anavar. GRAPES is similar in spirit to polyDFE, but slightly different in the details. anavar was really developed with indels in mind, although the model can be simplified to SNPs. I suspect anavar will be les widely used than any of the other tools we're testing.

Also bringing in @izabelcavassim , in case she has a strong opinion.

**Comment by izabelcavassim** [comment]
As far as I remember, polydfe is not capable of handling large sample sizes and I believe Paula Tataru (the developer) is not really maintaining it (she is working at QIAGEN). So to say that [GRAPES](https://github.com/BioPP/grapes) (maintained by Galtier and Julien Y. Dutheil?) would be a good option to include. Grapes also allows positive selection, and it has a bunch of distributions already pre-defined. I don't know anavar so I can't give an opinion about it.

**Comment by xin-huang** [comment]
Should we also include Parul's method https://github.com/paruljohri/BGS_Demography_DFE ?
Then we simulate data using continuous DFEs and test how discrete DFEs fit the data?

**Comment by chriscrsmith** [comment]
Sharing my notes where I'm saving some of this info. Not meant to be final:

**dadi**
	⁃	paper: Kim BY, Huber CD, Lohmueller KE. Inference of the distribution of selection coefficients for new nonsynonymous mutations using large samples. Genetics. 2017 May 1;206(1):345-61.
	⁃	year: 2017
	⁃	citations: 97
	⁃	notes: (we’re including this one)

**polyDFE**
	⁃	paper: Tataru P, Bataillon T. polyDFE: inferring the distribution of fitness effects and properties of beneficial mutations from polymorphism data. InStatistical Population Genomics 2020 (pp. 125-146). Humana, New York, NY.
	⁃	year: 2020
	⁃	citations: 3
	⁃	notes: dadi performs better with large sample size and polyDFE performs better with small sample size and nuisance parameters. polydfe is not capable of handling large sample sizes, and maybe not actively maintained.

**DFE-alpha**
	⁃	paper: Keightley PD, Eyre-Walker A. Joint inference of the distribution of fitness effects of deleterious mutations and population demography based on nucleotide polymorphism frequencies. Genetics. 2007 Dec 1;177(4):2251-61.
	⁃	year: 2007
	⁃	citations: 324
	⁃	notes: is widely used for inferring DFEs in different species, but it looks like E|s| is overestimated in DFE-alpha.

**Grapes**
	⁃	paper: Galtier N. Adaptive protein evolution in animals and the effective population size hypothesis. PLoS genetics. 2016 Jan 11;12(1):e1005774.
	⁃	year: 2016
	⁃	citations: 128
	⁃	notes: Grapes also allows positive selection, and it has a bunch of distributions already pre-defined

**Anovar**
	⁃	paper: Barton HJ, Zeng K. New methods for inferring the distribution of fitness effects for INDELs and SNPs. Molecular biology and evolution. 2018 Jun 1;35(6):1536-46.
	⁃	year: 2018
	⁃	citations: 18
	⁃	notes: focused more on indels; we don’t want to go there

**Johri et al 2020**
	⁃	paper: Johri P, Charlesworth B, Jensen JD. Toward an evolutionarily appropriate null model: Jointly inferring demography and purifying selection. Genetics. 2020 May 1;215(1):173-92.
	⁃	year: 2020
	⁃	citations: 34
	⁃	notes: Uses R ‘abc’ to estimate DFE and population history together. Seems less straightforward to implement compared to the other options.

**Comment by xin-huang** [comment]
implemented by https://github.com/popsim-consortium/analysis2/pull/43
