### ISSUE TITLE
Investigating SFSs with selection 

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/analysis2#35]
Started the analyses of the second paper on simulating genomes with selection.
Analyses are here for now: https://github.com/izabelcavassim/analysis2/blob/main/n_t_with_s/Snakefile
Three simulations datasets are defined based on selection as:

```
        if selection == "exons":
            ## Adding annotation only seletion on exon region
            exons = species.get_annotations(annotation_id)
            exon_intervals = exons.get_chromosome_annotations(wildcards.chrms)
            contig.add_dfe(intervals=exon_intervals, DFE=dfe)

        if selection == "all":
            # Adding selection to the whole contig
            contig.add_dfe(intervals=np.array([[0, int(contig.length)]]), DFE=dfe)

        if selection == "none":
            # if selection is not specified then a neutral model is expected
            contig = species.get_contig(wildcards.chrms, genetic_map=genetic_map_id)

        ###### Note that scaling factor is set to 10 (for now).
        ts = engine.simulate(model, contig, samples, seed=wildcards.seeds, slim_scaling_factor=10,
            slim_burn_in=10)
        ts.dump(output[0])
```

To compute the SFS (of the whole dataset) I do as follows, ts_p is the path to the ts.tree object:
https://github.com/izabelcavassim/analysis2/blob/main/n_t_with_s/stairway.py#L47

Plotting SFSs:
https://github.com/izabelcavassim/analysis2/blob/main/n_t_with_s/plots.py#L212

So far what we get from these three datasets is the following:
<img width="1067" alt="Screenshot 2022-02-08 at 11 29 02" src="https://user-images.githubusercontent.com/7824905/153061294-cd34e5a5-4e60-45f7-acd2-e87ac0380a0b.png">

The selection portion is the opposite of what we would expect (at least for the strong negative selection the SFS looks more like something that is strongly positive than negative).

Checks and TODOs:

- [x] If we are truly simulating a negative DFE
- [x] Separate the two SFSs in synonymous and nonsynonymous, at we take the synonymous portion to compute inference
- [x] Use slim logfile to get some statistics about the population (mean and sd fitness)
- [ ] Calculate Tajima's D across the whole dataset, example of function [here ](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence.Tajimas_D)

**Comment by izabelcavassim** [comment]
@petrelharp @mufernando tagging you guys here just so to brainstorm and help me out. Thanks

**Comment by petrelharp** [comment]
https://github.com/popsim-consortium/stdpopsim/issues/1190

**Comment by petrelharp** [comment]
Code to make SFS plots is [here](https://github.com/popsim-consortium/analysis2/blob/9869a9c72dbcd1b41f8616554e7eefeda9fc4d1a/workflows/plots.py#L232) (in `plots.py`); I don't think we need Tajima's D. Closing!
