### ISSUE TITLE
restructure analysis

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/analysis2#38]
currently the directory structure of `analysis2` could use some work. @xin-huang's recent PR #31 has two snakefiles that live in `benchmark`, and each of those has associated, hard-coded config files.  On the other hand @izabelcavassim's #30 brought in demographic analysis to a different directory `n_t_with_s` which has it's own snakefile, and as of yet, no dedicated config file (but instead an example of one and instructions on how to use it). 

I propose that we bring the `n_t_with_s` workflow, into a common folder with the other workflows and we adopt the paradigm of having a set of hard coded config files that we can share. for instance, i don't see a reason why the `n_t` workflow can't be using the simulations generated currently with `benchmark/simulation.snake`.

The idea would be to just have a single directory that defines all of the workflows to be done. We'll have to shuffle some names around but that won't be difficult. What do others think? I'm happy to draft up a PR if others like the idea

**Comment by izabelcavassim** [comment]
I am fine with that idea, maybe we could work on that tomorrow? I have some other things I wanna include as well, will be doing that today. And I am also including a config file.

**Comment by andrewkern** [comment]
@izabelcavassim I wouldn't add anything further until we talk more. I worked a little on a new PR I will be submitting towards this last night. please see here: https://github.com/andrewkern/analysis2/tree/merge_analysis_flow

**Comment by andrewkern** [comment]
also please note that I already added a config file to the `n_t_with_s` directory last week: https://github.com/popsim-consortium/analysis2/blob/main/n_t_with_s/test/config.json

**Comment by andrewkern** [comment]
closed by #40
