### ISSUE TITLE
Add msmc2 as a replacement of msmc

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/analysis2#48]
repository: https://github.com/stschiff/msmc2

I believe the command line is quite similar to the previous version

**Comment by chriscrsmith** [comment]
Looking into msmc2, got it installed. It requires D language compiler + gsl, also the git repo reads "DISCLAIMER: MSMC2 is under development. Use at your own risk!"

Checking in with folks to see if msmc2 still sounds like a good idea?

**Comment by chriscrsmith** [comment]
Stephan Schiffels says the message was old, it should be good to go.

PR #56

**Comment by andrewkern** [comment]
Okay @chriscrsmith -- #60 just got merged so we are ready for the new msmc swap.

**Comment by andrewkern** [comment]
closed by #65
