### ISSUE TITLE
Distribution of dominance coefficients implemented?

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/analysis2#5]
In the readme of this repo, we have `h = 0.5 / (1 - 7071.07 * gamma_mean)  # dominance coefficient`. However, in the Kim paper this line defines a function `h(s) = 0.5 / (1 - 7071.07 * s)` where `h` depends on the drawn selection coefficient. Looking at the `MutationClass` type in `selection.py`, I think it only supports a single dominance coefficient, so we'd probably want to set it just to 0.5 before QCing the implementation here of the Kim DFE.

**Comment by grahamgower** [comment]
Yep, right you are. It was potentially a lot of extra work to implement this properly, so I just made that compromise.

**Comment by apragsdale** [comment]
I think that's perfectly fine - variable dominance coefficients as a function of selection is interesting, but maybe well beyond what we want to get working at first. Setting h=0.5 might be all we end up exploring in this analysis anyway.

**Comment by grahamgower** [comment]
There was some discussion of this last year in the stdpopsim repo: https://github.com/popsim-consortium/stdpopsim/issues/588
