### ISSUE TITLE
Make sure smc++ works within our analysis2 env

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/analysis2#50]
We were/are having some problems installing smcpp within conda because support was discontinued since first paper.
Jonathan Terhorst is working on it and once we get it fixed we just need to add it to the environment.yml [here](https://github.com/popsim-consortium/analysis2/blob/main/environment.yml).

**Comment by petrelharp** [comment]
Any luck here, @terhorst?

**Comment by terhorst** [comment]
Thanks, understood.

**Comment by andrewkern** [comment]
yep i can confirm that i was able to build this as well.
