### ISSUE TITLE
list of final things to run the analysis on

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#66]
For the final analysis in this paper, we need to decide which:
- species
- demographic models
- genetic maps
- DFEs
- annotations that the DFEs apply to

**Comment by andrewkern** [comment]
along these lines-- what should the final masking be?

i propose we mask low recombination regions (as defined in analysis v1) as well as the matching annotation class that the data were simulated under. This assumes perfect knowledge of which sites have non-zero DFEs, which is of course unlikely to ever be the case, but perhaps good enough for the purposes of this paper.
