### ISSUE TITLE
A potential bug in stairway plot N(t) analysis?

### ISSUE THREAD

**Issue by lntran26** [popsim-consortium/analysis2#71]
When running the N(t) analysis on two demographic models "Constant" and Out-Of-Africa (YRI), @emanuelmfonseca and I noticed that the stairway plot results for these models are virtually identical (while msmc and GONE results do differ). @lauterbur noticed this on one of the calls where we showed the initial 1 rep result. We confirm that this happens consistently across different runs and on multiple replicates.

I also found that when running multiple replicates, the number of lines plotted for stairway plots using the current pipeline often don't match with the number of replicates specified in the config file, while msmc and GONE always do. Since `tiny_config.yaml` currently only have 1 rep and 1 demography these issues might be missed when debugging.

![constant_all_estimated_Ne](https://user-images.githubusercontent.com/38679445/183715691-4b6b2a88-8128-474f-aa66-645f360e8344.png)
![OOF_all_estimated_Ne](https://user-images.githubusercontent.com/38679445/183715698-c8014eb6-ef2d-42d4-92b3-ca2ee05b6ef2.png)

**Comment by andrewkern** [comment]
ah okay! this should be an easy enough bug fix. have you spotted the source of the issue yet?

**Comment by andrewkern** [comment]
I found the bug. The list of files stairwayplot intermediate files being handed to the `all_plot` rule was incorrect, and had a list of all demographic models used. I will submit a simple PR to fix this.

**Comment by lntran26** [comment]
Thank you @andrewkern !  @emanuelmfonseca and I have attempted to find/fix the bug ourselves but have been unsuccessful. Glad you can find it rather quickly!

**Comment by andrewkern** [comment]
@lntran26 I just authored a PR to fix this.
