### ISSUE TITLE
make plots of pi (and other things?) in windows along the genome from simulations

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#88]
We'd like to show, in the paper, a comparison of diversity in windows along a chromosome between (a) a neutral simulation, and (b) with a DFE acting on exons. Hopefully the reduction in pi will be in the ballpark of what's seen in real data (but I think that actually producing this plot for real data is beyond the scope of this paper) - what' s a good reference for that? (perhaps @mufernando's paper, as it should be preprinted before this one?)

**Comment by chriscrsmith** [comment]
I could work on this next week

**Comment by andrewkern** [comment]
ack yes-- and I just learned that @mufernando also may have started this!

**Comment by andrewkern** [comment]
have a PR up for this at #91

**Comment by andrewkern** [comment]
closed by #91
